### ISSUE TITLE
...

### ISSUE THREAD

**Issue by cheditx** [DrDesten/Stracciatella#9]
Why is this repo called like an italian food lol?

**Comment by DrDesten** [comment]
Stracciatella is a shader for Minecraft: Java Edition.
The name comes from "Stracciatella" Ice Cream, otherwise known as "Vanilla Chocolate Chip".

Stracciatella is meant to be an improvement to *vanilla* Minecraft, adding and improving graphics fidelity and customisability - analogous to how Stracciatella Ice Cream adds to Vanilla Ice Cream.

That's where the name comes from, I hope that answers your question.
